# Generated by Django 3.2.9 on 2024-01-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240124_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorVariet',
            new_name='ColorVariant',
        ),
        migrations.RenameModel(
            old_name='SizeVariet',
            new_name='SizeVariant',
        ),
    ]
