# Generated by Django 3.2.9 on 2024-01-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240124_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color_varient',
            new_name='color_variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_varient',
            new_name='size_variant',
        ),
    ]
